### ISSUE TITLE
DLL ACBrPosPrinter64

### ISSUE THREAD

**Issue by san0suke** [GabrielF7/ACBrTrunk2#2]
No exemplo do Java Pos printer está faltando a DLL: ACBrPosPrinter64

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Unable to load library 'ACBrPosPrinter64': Native library (win32-x86-64/ACBrPosPrinter64.dll) not found in resource path ([file:/D:/projetos/Java/Import/ACBrLibPosPrinter/build/classes/, file:/D:/projetos/Java/Import/ACBrLibPosPrinter/Libs/jna-4.5.1.jar, file:/D:/projetos/Java/Import/ACBrLibPosPrinter/Libs/jna-platform-4.5.1.jar, file:/D:/projetos/Java/Demo/ACBrLibPosPrinter.Demo/Dlls/, file:/D:/projetos/Java/Demo/ACBrLibPosPrinter.Demo/build/classes/])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at com.acbr.posprinter.ACBrPosPrinter$LibraryLoader.getInstance(ACBrPosPrinter.java:32)
	at com.acbr.posprinter.ACBrPosPrinter.<clinit>(ACBrPosPrinter.java:14)
	at com.acbr.demo.FrmMain.formWindowOpened(FrmMain.java:637)
	at com.acbr.demo.FrmMain.access$000(FrmMain.java:24)
	at com.acbr.demo.FrmMain$1.windowOpened(FrmMain.java:246)

**Comment by GabrielF7** [comment]
Colega, obrigado pelo seu report, mas não sou commiter no projeto ACBr, por isso não recebo sugestões/correções por aqui. Mantenho apenas como mirror mesmo. Por favor, adicione seu issue ao fórum oficial: https://www.projetoacbr.com.br/forum/
